### ISSUE TITLE
XML External Entity Attacks (XXE)  : "An error occured!"

### ISSUE THREAD

**Issue by 1070148808** [raesene/bWAPP#4]
1: XML External Entity Attacks (XXE)
always show "An error occured!",
this is script 
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root [
 <!ENTITY bWAPP SYSTEM "http://localhost/bWAPP/robots.txt">
]>
<reset><login>&bWAPP;</login><secret>blah</secret></reset>
```
and
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE copyright [
<!ENTITY test SYSTEM "123">
]>
<reset>
  <login>&test;</login>
  <secret>login</secret>
</reset>
```

look in the source code , then 

```
include("security.php");
include("security_level_check.php");
include("connect_i.php");

$message = "";
$body = file_get_contents("php://input");

// If the security level is not MEDIUM or HIGH
if($_COOKIE["security_level"] != "1" && $_COOKIE["security_level"] != "2")
{

    ini_set("display_errors",1);

    $xml = simplexml_load_string($body);

    // Debugging
    // print_r($xml);

    $login = $xml->login;
    $secret = $xml->secret;

    if($login && $login != "" && $secret)
    {

        // $login = mysqli_real_escape_string($link, $login);
        // $secret = mysqli_real_escape_string($link, $secret);
        
        $sql = "UPDATE users SET secret = '" . $secret . "' WHERE login = '" . $login . "'";

        // Debugging
        // echo $sql;      

        $recordset = $link->query($sql);

        if(!$recordset)
        {

            die("Connect Error: " . $link->error);

        }

        $message = $login . "'s secret has been reset!";

    }

    else
    {

        $message = "An error occured!";
        **$message = $xml;**

    }

}
```

add code 

`        $message = $xml;`
find can not read xml entity,
so , how to solve

-------------------------------------------
i already open php url include option

**Comment by srikr** [comment]
I am also hitting the same issue, Any solution for this?
![XXE-Error](https://user-images.githubusercontent.com/49506666/64634645-52cec980-d41b-11e9-8122-92b4dcf8175c.png)

**Comment by champlexi** [comment]
You need make following changes in xxe2.php

$xml = simplexml_load_string($body,'SimpleXMLElement', LIBXML_NOENT);

**Comment by vbisbest** [comment]
This is so odd because I swear it worked at one point.

**Comment by champlexi** [comment]
yeah it worked earlier but new changes in PHP7 does not support it.

**Comment by BBB-man** [comment]
thanks, I solve the problem with the following method.
>>>
You need make following changes in xxe2.php
$xml = simplexml_load_string($body,'SimpleXMLElement', LIBXML_NOENT);

**Comment by ghost** [comment]
Hello,

Does anyone have a solution for this issue? & Quelqu'un a-t-il une solution à ce problème ?
