### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by halfluke** [raesene/bWAPP#9]
What happened? It was used to work.

docker logs bb6d46ad8c9c
standard_init_linux.go:211: exec user process caused "no such file or directory"

run.sh does not exist anywhere in the source code...

**Comment by halfluke** [comment]
I apologize, clearly not a problem with the image and run.sh is in the base image, not in the bwapp source code.
Something went wrong with my docker, it happened with at least another image too.
A google search returns a lot of results talking about CRLF / LF conversion but I can't understand how they would apply to an image downloaded directly from dockerhub.
It has started working again for me now but not understanding what went awry is not a good feeling...

**Comment by zer-far** [comment]
If you are done with this can you close this issue?
